import { Body } from "@/components/Body";
import { Header } from "@/components/Header";
import Head from "next/head";
import Script from "next/script";
import { Suspense, useEffect } from "react";

export default function Home() {
  const start = Date.now();
  while (Date.now() - start < 50) {}
  console.log("SLOW PAGE START", performance.now());
  useEffect(() => {
    console.log("SLOW PAGE HYDRATE", performance.now());
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script strategy={"beforeInteractive"} src="./script.js" />
      <Suspense>
        <main
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <Suspense>
            <Header />
          </Suspense>

          <h1>Slow Page</h1>
          <Body />
        </main>
      </Suspense>
    </>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {},
  };
};
